CREATE TABLE IF NOT EXISTS test.users(
    id VARCHAR(255) NOT NULL,
    login VARCHAR(30) NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    pwd VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS test.players(
    id VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    img VARCHAR(255) NOT NULL,
    misc VARCHAR(255) NOT NULL,
    elo DOUBLE UNSIGNED NOT NULL DEFAULT 1200,
    k INT UNSIGNED NOT NULL DEFAULT 40,
    matchs INT UNSIGNED NOT NULL DEFAULT 0,
    nextPossibleMatch INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS test.parameters(
    name VARCHAR(100) NOT NULL,
    value BIGINT NOT NULL DEFAULT 0
);
INSERT INTO parameters (name,value) VALUES('totalMatchs', 0);